#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f *.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace f1_delay.sv clktick.sv f1_fsm.sv --exe clktick_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vf1_delay.mk Vf1_delay

# run executable simulation file
echo "\nRunning simulation"
obj_dir/Vf1_delay
echo "\nSimulation completed"

